language: python
python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pip install -v -e .
  - mkdir ~/tmp
  - cp pred_tstar/data/model4taup10.nd ~/tmp/
  - cd ~/tmp
  - python -m pred_tstar.pred_tstar ./model4taup10.nd --times 200 300
